games:
  - name: "Dűne: Impérium - Felkelés"
    url: "https://tarsasjatekok.com/tarsasjatek/dune-imperium-felkeles-2023"
  - name: "Gyűrűk Ura: Párbaj Középföldért"
    url: "https://tarsasjatekok.com/tarsasjatek/a-gyuruk-ura-parbaj-kozepfoldeert-2024"
  - name: "Világrend"
    url: "https://tarsasjatekok.com/tarsasjatek/vilagrend-2024"
  - name: "Tudattalan mélyén" 
    url:"https://tarsasjatekok.com/tarsasjatek/a-tudattalan-melyen-2022"
 
smtp:
  host: smtp.gmail.com
  port: 587
  use_tls: true
  username: boardgamepricecheck@gmail.com
  from: boardgamepricecheck@gmail.com

state_path: state.json
subject: "Daily board-game report"
